# 项目环境
spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /springboot
  port: 8080

superman:
  name: Karl
  age: 28
  birthday: 1991/06/25
  skill:
    - wind
    - fire
    - electric
    - water
  hobby:
    first: basketball
    second: computer
    third: footer
  weapon:
    name: alpheus
    category: sword
